export interface TailwindEntry {
  class: string
  css: string
}

export interface TailwindSection {
  title: string
  entries: TailwindEntry[]
}

export const SECTIONS: TailwindSection[] = [
  // ─── LAYOUT ───────────────────────────────────────────────────────────────
  {
    title: "Display",
    entries: [
      { class: "block", css: "display: block" },
      { class: "inline-block", css: "display: inline-block" },
      { class: "inline", css: "display: inline" },
      { class: "flex", css: "display: flex" },
      { class: "inline-flex", css: "display: inline-flex" },
      { class: "grid", css: "display: grid" },
      { class: "inline-grid", css: "display: inline-grid" },
      { class: "contents", css: "display: contents" },
      { class: "list-item", css: "display: list-item" },
      { class: "hidden", css: "display: none" },
      { class: "table", css: "display: table" },
      { class: "table-row", css: "display: table-row" },
      { class: "table-cell", css: "display: table-cell" },
    ],
  },
  {
    title: "Position",
    entries: [
      { class: "static", css: "position: static" },
      { class: "relative", css: "position: relative" },
      { class: "absolute", css: "position: absolute" },
      { class: "fixed", css: "position: fixed" },
      { class: "sticky", css: "position: sticky" },
      { class: "inset-0", css: "inset: 0px" },
      { class: "inset-auto", css: "inset: auto" },
      { class: "inset-x-0", css: "left: 0px; right: 0px" },
      { class: "inset-y-0", css: "top: 0px; bottom: 0px" },
      { class: "top-0", css: "top: 0px" },
      { class: "right-0", css: "right: 0px" },
      { class: "bottom-0", css: "bottom: 0px" },
      { class: "left-0", css: "left: 0px" },
      { class: "top-auto", css: "top: auto" },
      { class: "top-1/2", css: "top: 50%" },
      { class: "top-full", css: "top: 100%" },
    ],
  },
  {
    title: "Visibility",
    entries: [
      { class: "visible", css: "visibility: visible" },
      { class: "invisible", css: "visibility: hidden" },
      { class: "collapse", css: "visibility: collapse" },
    ],
  },
  {
    title: "Z-Index",
    entries: [
      { class: "z-0", css: "z-index: 0" },
      { class: "z-10", css: "z-index: 10" },
      { class: "z-20", css: "z-index: 20" },
      { class: "z-30", css: "z-index: 30" },
      { class: "z-40", css: "z-index: 40" },
      { class: "z-50", css: "z-index: 50" },
      { class: "z-auto", css: "z-index: auto" },
    ],
  },
  {
    title: "Overflow",
    entries: [
      { class: "overflow-auto", css: "overflow: auto" },
      { class: "overflow-hidden", css: "overflow: hidden" },
      { class: "overflow-clip", css: "overflow: clip" },
      { class: "overflow-visible", css: "overflow: visible" },
      { class: "overflow-scroll", css: "overflow: scroll" },
      { class: "overflow-x-auto", css: "overflow-x: auto" },
      { class: "overflow-y-auto", css: "overflow-y: auto" },
      { class: "overflow-x-hidden", css: "overflow-x: hidden" },
      { class: "overflow-y-hidden", css: "overflow-y: hidden" },
      { class: "overflow-x-scroll", css: "overflow-x: scroll" },
      { class: "overflow-y-scroll", css: "overflow-y: scroll" },
    ],
  },
  {
    title: "Overscroll Behavior",
    entries: [
      { class: "overscroll-auto", css: "overscroll-behavior: auto" },
      { class: "overscroll-contain", css: "overscroll-behavior: contain" },
      { class: "overscroll-none", css: "overscroll-behavior: none" },
      { class: "overscroll-y-auto", css: "overscroll-behavior-y: auto" },
      { class: "overscroll-y-contain", css: "overscroll-behavior-y: contain" },
      { class: "overscroll-x-none", css: "overscroll-behavior-x: none" },
    ],
  },
  {
    title: "Box Sizing",
    entries: [
      { class: "box-border", css: "box-sizing: border-box" },
      { class: "box-content", css: "box-sizing: content-box" },
    ],
  },
  {
    title: "Float & Clear",
    entries: [
      { class: "float-start", css: "float: inline-start" },
      { class: "float-end", css: "float: inline-end" },
      { class: "float-right", css: "float: right" },
      { class: "float-left", css: "float: left" },
      { class: "float-none", css: "float: none" },
      { class: "clear-start", css: "clear: inline-start" },
      { class: "clear-end", css: "clear: inline-end" },
      { class: "clear-left", css: "clear: left" },
      { class: "clear-right", css: "clear: right" },
      { class: "clear-both", css: "clear: both" },
      { class: "clear-none", css: "clear: none" },
    ],
  },
  {
    title: "Isolation",
    entries: [
      { class: "isolate", css: "isolation: isolate" },
      { class: "isolation-auto", css: "isolation: auto" },
    ],
  },
  {
    title: "Object Fit",
    entries: [
      { class: "object-contain", css: "object-fit: contain" },
      { class: "object-cover", css: "object-fit: cover" },
      { class: "object-fill", css: "object-fit: fill" },
      { class: "object-none", css: "object-fit: none" },
      { class: "object-scale-down", css: "object-fit: scale-down" },
    ],
  },
  {
    title: "Object Position",
    entries: [
      { class: "object-bottom", css: "object-position: bottom" },
      { class: "object-center", css: "object-position: center" },
      { class: "object-left", css: "object-position: left" },
      { class: "object-left-bottom", css: "object-position: left bottom" },
      { class: "object-left-top", css: "object-position: left top" },
      { class: "object-right", css: "object-position: right" },
      { class: "object-right-bottom", css: "object-position: right bottom" },
      { class: "object-right-top", css: "object-position: right top" },
      { class: "object-top", css: "object-position: top" },
    ],
  },
  {
    title: "Aspect Ratio",
    entries: [
      { class: "aspect-auto", css: "aspect-ratio: auto" },
      { class: "aspect-square", css: "aspect-ratio: 1 / 1" },
      { class: "aspect-video", css: "aspect-ratio: 16 / 9" },
    ],
  },
  {
    title: "Columns",
    entries: [
      { class: "columns-1", css: "columns: 1" },
      { class: "columns-2", css: "columns: 2" },
      { class: "columns-3", css: "columns: 3" },
      { class: "columns-auto", css: "columns: auto" },
      { class: "columns-3xs", css: "columns: 16rem" },
      { class: "columns-xs", css: "columns: 20rem" },
      { class: "columns-sm", css: "columns: 24rem" },
      { class: "columns-md", css: "columns: 28rem" },
    ],
  },
  {
    title: "Break",
    entries: [
      { class: "break-after-auto", css: "break-after: auto" },
      { class: "break-after-avoid", css: "break-after: avoid" },
      { class: "break-after-all", css: "break-after: all" },
      { class: "break-after-page", css: "break-after: page" },
      { class: "break-before-auto", css: "break-before: auto" },
      { class: "break-before-page", css: "break-before: page" },
      { class: "break-inside-auto", css: "break-inside: auto" },
      { class: "break-inside-avoid", css: "break-inside: avoid" },
      { class: "break-inside-avoid-page", css: "break-inside: avoid-page" },
      { class: "break-inside-avoid-column", css: "break-inside: avoid-column" },
    ],
  },
  {
    title: "Container",
    entries: [
      {
        class: "container",
        css: "width: 100%; max-width per breakpoint (sm→640px, md→768px, lg→1024px, xl→1280px, 2xl→1536px)",
      },
    ],
  },
  // ─── FLEXBOX ──────────────────────────────────────────────────────────────
  {
    title: "Flex Direction",
    entries: [
      { class: "flex-row", css: "flex-direction: row" },
      { class: "flex-row-reverse", css: "flex-direction: row-reverse" },
      { class: "flex-col", css: "flex-direction: column" },
      { class: "flex-col-reverse", css: "flex-direction: column-reverse" },
    ],
  },
  {
    title: "Flex Wrap",
    entries: [
      { class: "flex-wrap", css: "flex-wrap: wrap" },
      { class: "flex-wrap-reverse", css: "flex-wrap: wrap-reverse" },
      { class: "flex-nowrap", css: "flex-wrap: nowrap" },
    ],
  },
  {
    title: "Flex",
    entries: [
      { class: "flex-1", css: "flex: 1 1 0%" },
      { class: "flex-auto", css: "flex: 1 1 auto" },
      { class: "flex-initial", css: "flex: 0 1 auto" },
      { class: "flex-none", css: "flex: none" },
    ],
  },
  {
    title: "Flex Grow & Shrink",
    entries: [
      { class: "grow", css: "flex-grow: 1" },
      { class: "grow-0", css: "flex-grow: 0" },
      { class: "shrink", css: "flex-shrink: 1" },
      { class: "shrink-0", css: "flex-shrink: 0" },
    ],
  },
  {
    title: "Flex Basis",
    entries: [
      { class: "basis-auto", css: "flex-basis: auto" },
      { class: "basis-0", css: "flex-basis: 0px" },
      { class: "basis-1/2", css: "flex-basis: 50%" },
      { class: "basis-1/3", css: "flex-basis: 33.333333%" },
      { class: "basis-1/4", css: "flex-basis: 25%" },
      { class: "basis-full", css: "flex-basis: 100%" },
    ],
  },
  {
    title: "Order",
    entries: [
      { class: "order-first", css: "order: -9999" },
      { class: "order-last", css: "order: 9999" },
      { class: "order-none", css: "order: 0" },
      { class: "order-1", css: "order: 1" },
      { class: "order-2", css: "order: 2" },
      { class: "order-3", css: "order: 3" },
    ],
  },
  // ─── ALIGNMENT ────────────────────────────────────────────────────────────
  {
    title: "Align Items",
    entries: [
      { class: "items-start", css: "align-items: flex-start" },
      { class: "items-end", css: "align-items: flex-end" },
      { class: "items-center", css: "align-items: center" },
      { class: "items-baseline", css: "align-items: baseline" },
      { class: "items-stretch", css: "align-items: stretch" },
    ],
  },
  {
    title: "Align Self",
    entries: [
      { class: "self-auto", css: "align-self: auto" },
      { class: "self-start", css: "align-self: flex-start" },
      { class: "self-end", css: "align-self: flex-end" },
      { class: "self-center", css: "align-self: center" },
      { class: "self-stretch", css: "align-self: stretch" },
      { class: "self-baseline", css: "align-self: baseline" },
    ],
  },
  {
    title: "Align Content",
    entries: [
      { class: "content-normal", css: "align-content: normal" },
      { class: "content-center", css: "align-content: center" },
      { class: "content-start", css: "align-content: flex-start" },
      { class: "content-end", css: "align-content: flex-end" },
      { class: "content-between", css: "align-content: space-between" },
      { class: "content-around", css: "align-content: space-around" },
      { class: "content-evenly", css: "align-content: space-evenly" },
      { class: "content-baseline", css: "align-content: baseline" },
      { class: "content-stretch", css: "align-content: stretch" },
    ],
  },
  {
    title: "Justify Content",
    entries: [
      { class: "justify-normal", css: "justify-content: normal" },
      { class: "justify-start", css: "justify-content: flex-start" },
      { class: "justify-end", css: "justify-content: flex-end" },
      { class: "justify-center", css: "justify-content: center" },
      { class: "justify-between", css: "justify-content: space-between" },
      { class: "justify-around", css: "justify-content: space-around" },
      { class: "justify-evenly", css: "justify-content: space-evenly" },
      { class: "justify-stretch", css: "justify-content: stretch" },
    ],
  },
  {
    title: "Justify Items",
    entries: [
      { class: "justify-items-start", css: "justify-items: start" },
      { class: "justify-items-end", css: "justify-items: end" },
      { class: "justify-items-center", css: "justify-items: center" },
      { class: "justify-items-stretch", css: "justify-items: stretch" },
    ],
  },
  {
    title: "Justify Self",
    entries: [
      { class: "justify-self-auto", css: "justify-self: auto" },
      { class: "justify-self-start", css: "justify-self: start" },
      { class: "justify-self-end", css: "justify-self: end" },
      { class: "justify-self-center", css: "justify-self: center" },
      { class: "justify-self-stretch", css: "justify-self: stretch" },
    ],
  },
  // ─── GRID ─────────────────────────────────────────────────────────────────
  {
    title: "Grid Template Columns",
    entries: [
      { class: "grid-cols-none", css: "grid-template-columns: none" },
      {
        class: "grid-cols-1",
        css: "grid-template-columns: repeat(1, minmax(0, 1fr))",
      },
      {
        class: "grid-cols-2",
        css: "grid-template-columns: repeat(2, minmax(0, 1fr))",
      },
      {
        class: "grid-cols-3",
        css: "grid-template-columns: repeat(3, minmax(0, 1fr))",
      },
      {
        class: "grid-cols-4",
        css: "grid-template-columns: repeat(4, minmax(0, 1fr))",
      },
      {
        class: "grid-cols-5",
        css: "grid-template-columns: repeat(5, minmax(0, 1fr))",
      },
      {
        class: "grid-cols-6",
        css: "grid-template-columns: repeat(6, minmax(0, 1fr))",
      },
      {
        class: "grid-cols-12",
        css: "grid-template-columns: repeat(12, minmax(0, 1fr))",
      },
      { class: "grid-cols-subgrid", css: "grid-template-columns: subgrid" },
    ],
  },
  {
    title: "Grid Column Span",
    entries: [
      { class: "col-auto", css: "grid-column: auto" },
      { class: "col-span-1", css: "grid-column: span 1 / span 1" },
      { class: "col-span-2", css: "grid-column: span 2 / span 2" },
      { class: "col-span-3", css: "grid-column: span 3 / span 3" },
      { class: "col-span-4", css: "grid-column: span 4 / span 4" },
      { class: "col-span-full", css: "grid-column: 1 / -1" },
      { class: "col-start-1", css: "grid-column-start: 1" },
      { class: "col-start-auto", css: "grid-column-start: auto" },
      { class: "col-end-1", css: "grid-column-end: 1" },
      { class: "col-end-auto", css: "grid-column-end: auto" },
    ],
  },
  {
    title: "Grid Template Rows",
    entries: [
      { class: "grid-rows-none", css: "grid-template-rows: none" },
      {
        class: "grid-rows-1",
        css: "grid-template-rows: repeat(1, minmax(0, 1fr))",
      },
      {
        class: "grid-rows-2",
        css: "grid-template-rows: repeat(2, minmax(0, 1fr))",
      },
      {
        class: "grid-rows-3",
        css: "grid-template-rows: repeat(3, minmax(0, 1fr))",
      },
      {
        class: "grid-rows-4",
        css: "grid-template-rows: repeat(4, minmax(0, 1fr))",
      },
      {
        class: "grid-rows-6",
        css: "grid-template-rows: repeat(6, minmax(0, 1fr))",
      },
      { class: "grid-rows-subgrid", css: "grid-template-rows: subgrid" },
    ],
  },
  {
    title: "Grid Row Span",
    entries: [
      { class: "row-auto", css: "grid-row: auto" },
      { class: "row-span-1", css: "grid-row: span 1 / span 1" },
      { class: "row-span-2", css: "grid-row: span 2 / span 2" },
      { class: "row-span-full", css: "grid-row: 1 / -1" },
      { class: "row-start-1", css: "grid-row-start: 1" },
      { class: "row-start-auto", css: "grid-row-start: auto" },
      { class: "row-end-1", css: "grid-row-end: 1" },
    ],
  },
  {
    title: "Grid Auto Flow",
    entries: [
      { class: "grid-flow-row", css: "grid-auto-flow: row" },
      { class: "grid-flow-col", css: "grid-auto-flow: column" },
      { class: "grid-flow-dense", css: "grid-auto-flow: dense" },
      { class: "grid-flow-row-dense", css: "grid-auto-flow: row dense" },
      { class: "grid-flow-col-dense", css: "grid-auto-flow: column dense" },
    ],
  },
  {
    title: "Grid Auto Columns/Rows",
    entries: [
      { class: "auto-cols-auto", css: "grid-auto-columns: auto" },
      { class: "auto-cols-min", css: "grid-auto-columns: min-content" },
      { class: "auto-cols-max", css: "grid-auto-columns: max-content" },
      { class: "auto-cols-fr", css: "grid-auto-columns: minmax(0, 1fr)" },
      { class: "auto-rows-auto", css: "grid-auto-rows: auto" },
      { class: "auto-rows-min", css: "grid-auto-rows: min-content" },
      { class: "auto-rows-max", css: "grid-auto-rows: max-content" },
      { class: "auto-rows-fr", css: "grid-auto-rows: minmax(0, 1fr)" },
    ],
  },
  // ─── GAP ──────────────────────────────────────────────────────────────────
  {
    title: "Gap",
    entries: [
      { class: "gap-0", css: "gap: 0px" },
      { class: "gap-px", css: "gap: 1px" },
      { class: "gap-0.5", css: "gap: 0.125rem" },
      { class: "gap-1", css: "gap: 0.25rem" },
      { class: "gap-2", css: "gap: 0.5rem" },
      { class: "gap-3", css: "gap: 0.75rem" },
      { class: "gap-4", css: "gap: 1rem" },
      { class: "gap-5", css: "gap: 1.25rem" },
      { class: "gap-6", css: "gap: 1.5rem" },
      { class: "gap-8", css: "gap: 2rem" },
      { class: "gap-10", css: "gap: 2.5rem" },
      { class: "gap-12", css: "gap: 3rem" },
      { class: "gap-16", css: "gap: 4rem" },
      { class: "gap-x-4", css: "column-gap: 1rem" },
      { class: "gap-y-4", css: "row-gap: 1rem" },
    ],
  },
  // ─── SPACING ──────────────────────────────────────────────────────────────
  {
    title: "Padding",
    entries: [
      { class: "p-0", css: "padding: 0px" },
      { class: "p-px", css: "padding: 1px" },
      { class: "p-0.5", css: "padding: 0.125rem" },
      { class: "p-1", css: "padding: 0.25rem" },
      { class: "p-1.5", css: "padding: 0.375rem" },
      { class: "p-2", css: "padding: 0.5rem" },
      { class: "p-2.5", css: "padding: 0.625rem" },
      { class: "p-3", css: "padding: 0.75rem" },
      { class: "p-4", css: "padding: 1rem" },
      { class: "p-5", css: "padding: 1.25rem" },
      { class: "p-6", css: "padding: 1.5rem" },
      { class: "p-8", css: "padding: 2rem" },
      { class: "p-10", css: "padding: 2.5rem" },
      { class: "p-12", css: "padding: 3rem" },
      { class: "p-16", css: "padding: 4rem" },
      { class: "px-4", css: "padding-left: 1rem; padding-right: 1rem" },
      { class: "py-4", css: "padding-top: 1rem; padding-bottom: 1rem" },
      { class: "ps-4", css: "padding-inline-start: 1rem" },
      { class: "pe-4", css: "padding-inline-end: 1rem" },
      { class: "pt-4", css: "padding-top: 1rem" },
      { class: "pr-4", css: "padding-right: 1rem" },
      { class: "pb-4", css: "padding-bottom: 1rem" },
      { class: "pl-4", css: "padding-left: 1rem" },
    ],
  },
  {
    title: "Margin",
    entries: [
      { class: "m-0", css: "margin: 0px" },
      { class: "m-auto", css: "margin: auto" },
      { class: "m-px", css: "margin: 1px" },
      { class: "m-1", css: "margin: 0.25rem" },
      { class: "m-2", css: "margin: 0.5rem" },
      { class: "m-4", css: "margin: 1rem" },
      { class: "m-6", css: "margin: 1.5rem" },
      { class: "m-8", css: "margin: 2rem" },
      { class: "mx-auto", css: "margin-left: auto; margin-right: auto" },
      { class: "mx-4", css: "margin-left: 1rem; margin-right: 1rem" },
      { class: "my-4", css: "margin-top: 1rem; margin-bottom: 1rem" },
      { class: "ms-auto", css: "margin-inline-start: auto" },
      { class: "me-auto", css: "margin-inline-end: auto" },
      { class: "mt-4", css: "margin-top: 1rem" },
      { class: "mr-4", css: "margin-right: 1rem" },
      { class: "mb-4", css: "margin-bottom: 1rem" },
      { class: "ml-4", css: "margin-left: 1rem" },
      { class: "-m-4", css: "margin: -1rem" },
      { class: "-mt-4", css: "margin-top: -1rem" },
    ],
  },
  {
    title: "Space Between",
    entries: [
      { class: "space-x-0", css: "margin-left: 0px (children)" },
      { class: "space-x-1", css: "margin-left: 0.25rem (children)" },
      { class: "space-x-2", css: "margin-left: 0.5rem (children)" },
      { class: "space-x-4", css: "margin-left: 1rem (children)" },
      { class: "space-x-8", css: "margin-left: 2rem (children)" },
      { class: "space-y-0", css: "margin-top: 0px (children)" },
      { class: "space-y-1", css: "margin-top: 0.25rem (children)" },
      { class: "space-y-2", css: "margin-top: 0.5rem (children)" },
      { class: "space-y-4", css: "margin-top: 1rem (children)" },
      { class: "space-y-8", css: "margin-top: 2rem (children)" },
      { class: "space-x-reverse", css: "--tw-space-x-reverse: 1" },
      { class: "space-y-reverse", css: "--tw-space-y-reverse: 1" },
    ],
  },
  // ─── SIZING ───────────────────────────────────────────────────────────────
  {
    title: "Width",
    entries: [
      { class: "w-auto", css: "width: auto" },
      { class: "w-0", css: "width: 0px" },
      { class: "w-px", css: "width: 1px" },
      { class: "w-1", css: "width: 0.25rem" },
      { class: "w-2", css: "width: 0.5rem" },
      { class: "w-4", css: "width: 1rem" },
      { class: "w-8", css: "width: 2rem" },
      { class: "w-16", css: "width: 4rem" },
      { class: "w-32", css: "width: 8rem" },
      { class: "w-48", css: "width: 12rem" },
      { class: "w-64", css: "width: 16rem" },
      { class: "w-1/2", css: "width: 50%" },
      { class: "w-1/3", css: "width: 33.333333%" },
      { class: "w-2/3", css: "width: 66.666667%" },
      { class: "w-1/4", css: "width: 25%" },
      { class: "w-3/4", css: "width: 75%" },
      { class: "w-full", css: "width: 100%" },
      { class: "w-screen", css: "width: 100vw" },
      { class: "w-svw", css: "width: 100svw" },
      { class: "w-dvw", css: "width: 100dvw" },
      { class: "w-min", css: "width: min-content" },
      { class: "w-max", css: "width: max-content" },
      { class: "w-fit", css: "width: fit-content" },
    ],
  },
  {
    title: "Min / Max Width",
    entries: [
      { class: "min-w-0", css: "min-width: 0px" },
      { class: "min-w-full", css: "min-width: 100%" },
      { class: "min-w-min", css: "min-width: min-content" },
      { class: "min-w-max", css: "min-width: max-content" },
      { class: "min-w-fit", css: "min-width: fit-content" },
      { class: "max-w-none", css: "max-width: none" },
      { class: "max-w-xs", css: "max-width: 20rem" },
      { class: "max-w-sm", css: "max-width: 24rem" },
      { class: "max-w-md", css: "max-width: 28rem" },
      { class: "max-w-lg", css: "max-width: 32rem" },
      { class: "max-w-xl", css: "max-width: 36rem" },
      { class: "max-w-2xl", css: "max-width: 42rem" },
      { class: "max-w-3xl", css: "max-width: 48rem" },
      { class: "max-w-4xl", css: "max-width: 56rem" },
      { class: "max-w-5xl", css: "max-width: 64rem" },
      { class: "max-w-6xl", css: "max-width: 72rem" },
      { class: "max-w-7xl", css: "max-width: 80rem" },
      { class: "max-w-full", css: "max-width: 100%" },
      { class: "max-w-screen-sm", css: "max-width: 640px" },
      { class: "max-w-screen-lg", css: "max-width: 1024px" },
      { class: "max-w-prose", css: "max-width: 65ch" },
      { class: "max-w-min", css: "max-width: min-content" },
      { class: "max-w-max", css: "max-width: max-content" },
      { class: "max-w-fit", css: "max-width: fit-content" },
    ],
  },
  {
    title: "Height",
    entries: [
      { class: "h-auto", css: "height: auto" },
      { class: "h-0", css: "height: 0px" },
      { class: "h-px", css: "height: 1px" },
      { class: "h-1", css: "height: 0.25rem" },
      { class: "h-2", css: "height: 0.5rem" },
      { class: "h-4", css: "height: 1rem" },
      { class: "h-8", css: "height: 2rem" },
      { class: "h-16", css: "height: 4rem" },
      { class: "h-32", css: "height: 8rem" },
      { class: "h-64", css: "height: 16rem" },
      { class: "h-1/2", css: "height: 50%" },
      { class: "h-full", css: "height: 100%" },
      { class: "h-screen", css: "height: 100vh" },
      { class: "h-svh", css: "height: 100svh" },
      { class: "h-dvh", css: "height: 100dvh" },
      { class: "h-min", css: "height: min-content" },
      { class: "h-max", css: "height: max-content" },
      { class: "h-fit", css: "height: fit-content" },
    ],
  },
  {
    title: "Min / Max Height",
    entries: [
      { class: "min-h-0", css: "min-height: 0px" },
      { class: "min-h-full", css: "min-height: 100%" },
      { class: "min-h-screen", css: "min-height: 100vh" },
      { class: "min-h-svh", css: "min-height: 100svh" },
      { class: "min-h-dvh", css: "min-height: 100dvh" },
      { class: "min-h-min", css: "min-height: min-content" },
      { class: "min-h-max", css: "min-height: max-content" },
      { class: "min-h-fit", css: "min-height: fit-content" },
      { class: "max-h-none", css: "max-height: none" },
      { class: "max-h-full", css: "max-height: 100%" },
      { class: "max-h-screen", css: "max-height: 100vh" },
      { class: "max-h-svh", css: "max-height: 100svh" },
      { class: "max-h-dvh", css: "max-height: 100dvh" },
      { class: "max-h-min", css: "max-height: min-content" },
      { class: "max-h-max", css: "max-height: max-content" },
      { class: "max-h-fit", css: "max-height: fit-content" },
    ],
  },
  {
    title: "Size",
    entries: [
      { class: "size-auto", css: "width: auto; height: auto" },
      { class: "size-0", css: "width: 0px; height: 0px" },
      { class: "size-1", css: "width: 0.25rem; height: 0.25rem" },
      { class: "size-4", css: "width: 1rem; height: 1rem" },
      { class: "size-8", css: "width: 2rem; height: 2rem" },
      { class: "size-full", css: "width: 100%; height: 100%" },
    ],
  },
  // ─── TYPOGRAPHY ───────────────────────────────────────────────────────────
  {
    title: "Font Family",
    entries: [
      {
        class: "font-sans",
        css: "font-family: ui-sans-serif, system-ui, sans-serif, ...",
      },
      {
        class: "font-serif",
        css: "font-family: ui-serif, Georgia, Cambria, ...",
      },
      {
        class: "font-mono",
        css: "font-family: ui-monospace, SFMono-Regular, ...",
      },
    ],
  },
  {
    title: "Font Size",
    entries: [
      { class: "text-xs", css: "font-size: 0.75rem; line-height: 1rem" },
      { class: "text-sm", css: "font-size: 0.875rem; line-height: 1.25rem" },
      { class: "text-base", css: "font-size: 1rem; line-height: 1.5rem" },
      { class: "text-lg", css: "font-size: 1.125rem; line-height: 1.75rem" },
      { class: "text-xl", css: "font-size: 1.25rem; line-height: 1.75rem" },
      { class: "text-2xl", css: "font-size: 1.5rem; line-height: 2rem" },
      { class: "text-3xl", css: "font-size: 1.875rem; line-height: 2.25rem" },
      { class: "text-4xl", css: "font-size: 2.25rem; line-height: 2.5rem" },
      { class: "text-5xl", css: "font-size: 3rem; line-height: 1" },
      { class: "text-6xl", css: "font-size: 3.75rem; line-height: 1" },
      { class: "text-7xl", css: "font-size: 4.5rem; line-height: 1" },
      { class: "text-8xl", css: "font-size: 6rem; line-height: 1" },
      { class: "text-9xl", css: "font-size: 8rem; line-height: 1" },
    ],
  },
  {
    title: "Font Weight",
    entries: [
      { class: "font-thin", css: "font-weight: 100" },
      { class: "font-extralight", css: "font-weight: 200" },
      { class: "font-light", css: "font-weight: 300" },
      { class: "font-normal", css: "font-weight: 400" },
      { class: "font-medium", css: "font-weight: 500" },
      { class: "font-semibold", css: "font-weight: 600" },
      { class: "font-bold", css: "font-weight: 700" },
      { class: "font-extrabold", css: "font-weight: 800" },
      { class: "font-black", css: "font-weight: 900" },
    ],
  },
  {
    title: "Font Style & Smoothing",
    entries: [
      { class: "italic", css: "font-style: italic" },
      { class: "not-italic", css: "font-style: normal" },
      {
        class: "antialiased",
        css: "-webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale",
      },
      {
        class: "subpixel-antialiased",
        css: "-webkit-font-smoothing: auto; -moz-osx-font-smoothing: auto",
      },
    ],
  },
  {
    title: "Letter Spacing",
    entries: [
      { class: "tracking-tighter", css: "letter-spacing: -0.05em" },
      { class: "tracking-tight", css: "letter-spacing: -0.025em" },
      { class: "tracking-normal", css: "letter-spacing: 0em" },
      { class: "tracking-wide", css: "letter-spacing: 0.025em" },
      { class: "tracking-wider", css: "letter-spacing: 0.05em" },
      { class: "tracking-widest", css: "letter-spacing: 0.1em" },
    ],
  },
  {
    title: "Line Height",
    entries: [
      { class: "leading-none", css: "line-height: 1" },
      { class: "leading-tight", css: "line-height: 1.25" },
      { class: "leading-snug", css: "line-height: 1.375" },
      { class: "leading-normal", css: "line-height: 1.5" },
      { class: "leading-relaxed", css: "line-height: 1.625" },
      { class: "leading-loose", css: "line-height: 2" },
      { class: "leading-3", css: "line-height: 0.75rem" },
      { class: "leading-4", css: "line-height: 1rem" },
      { class: "leading-5", css: "line-height: 1.25rem" },
      { class: "leading-6", css: "line-height: 1.5rem" },
      { class: "leading-7", css: "line-height: 1.75rem" },
      { class: "leading-8", css: "line-height: 2rem" },
      { class: "leading-10", css: "line-height: 2.5rem" },
    ],
  },
  {
    title: "Line Clamp",
    entries: [
      {
        class: "line-clamp-1",
        css: "overflow: hidden; display: -webkit-box; -webkit-line-clamp: 1; -webkit-box-orient: vertical",
      },
      { class: "line-clamp-2", css: "-webkit-line-clamp: 2" },
      { class: "line-clamp-3", css: "-webkit-line-clamp: 3" },
      { class: "line-clamp-4", css: "-webkit-line-clamp: 4" },
      { class: "line-clamp-6", css: "-webkit-line-clamp: 6" },
      {
        class: "line-clamp-none",
        css: "overflow: visible; display: block; -webkit-line-clamp: unset",
      },
    ],
  },
  {
    title: "Text Align",
    entries: [
      { class: "text-left", css: "text-align: left" },
      { class: "text-center", css: "text-align: center" },
      { class: "text-right", css: "text-align: right" },
      { class: "text-justify", css: "text-align: justify" },
      { class: "text-start", css: "text-align: start" },
      { class: "text-end", css: "text-align: end" },
    ],
  },
  {
    title: "Text Decoration",
    entries: [
      { class: "underline", css: "text-decoration-line: underline" },
      { class: "overline", css: "text-decoration-line: overline" },
      { class: "line-through", css: "text-decoration-line: line-through" },
      { class: "no-underline", css: "text-decoration-line: none" },
      { class: "decoration-solid", css: "text-decoration-style: solid" },
      { class: "decoration-double", css: "text-decoration-style: double" },
      { class: "decoration-dotted", css: "text-decoration-style: dotted" },
      { class: "decoration-dashed", css: "text-decoration-style: dashed" },
      { class: "decoration-wavy", css: "text-decoration-style: wavy" },
      { class: "decoration-auto", css: "text-decoration-thickness: auto" },
      { class: "decoration-1", css: "text-decoration-thickness: 1px" },
      { class: "decoration-2", css: "text-decoration-thickness: 2px" },
      { class: "underline-offset-auto", css: "text-underline-offset: auto" },
      { class: "underline-offset-1", css: "text-underline-offset: 1px" },
      { class: "underline-offset-4", css: "text-underline-offset: 4px" },
    ],
  },
  {
    title: "Text Transform",
    entries: [
      { class: "uppercase", css: "text-transform: uppercase" },
      { class: "lowercase", css: "text-transform: lowercase" },
      { class: "capitalize", css: "text-transform: capitalize" },
      { class: "normal-case", css: "text-transform: none" },
    ],
  },
  {
    title: "Text Overflow",
    entries: [
      {
        class: "truncate",
        css: "overflow: hidden; text-overflow: ellipsis; white-space: nowrap",
      },
      { class: "text-ellipsis", css: "text-overflow: ellipsis" },
      { class: "text-clip", css: "text-overflow: clip" },
    ],
  },
  {
    title: "Text Wrap",
    entries: [
      { class: "text-wrap", css: "text-wrap: wrap" },
      { class: "text-nowrap", css: "text-wrap: nowrap" },
      { class: "text-balance", css: "text-wrap: balance" },
      { class: "text-pretty", css: "text-wrap: pretty" },
    ],
  },
  {
    title: "Text Indent",
    entries: [
      { class: "indent-0", css: "text-indent: 0px" },
      { class: "indent-px", css: "text-indent: 1px" },
      { class: "indent-4", css: "text-indent: 1rem" },
      { class: "indent-8", css: "text-indent: 2rem" },
    ],
  },
  {
    title: "Vertical Align",
    entries: [
      { class: "align-baseline", css: "vertical-align: baseline" },
      { class: "align-top", css: "vertical-align: top" },
      { class: "align-middle", css: "vertical-align: middle" },
      { class: "align-bottom", css: "vertical-align: bottom" },
      { class: "align-text-top", css: "vertical-align: text-top" },
      { class: "align-text-bottom", css: "vertical-align: text-bottom" },
      { class: "align-sub", css: "vertical-align: sub" },
      { class: "align-super", css: "vertical-align: super" },
    ],
  },
  {
    title: "Whitespace",
    entries: [
      { class: "whitespace-normal", css: "white-space: normal" },
      { class: "whitespace-nowrap", css: "white-space: nowrap" },
      { class: "whitespace-pre", css: "white-space: pre" },
      { class: "whitespace-pre-line", css: "white-space: pre-line" },
      { class: "whitespace-pre-wrap", css: "white-space: pre-wrap" },
      { class: "whitespace-break-spaces", css: "white-space: break-spaces" },
    ],
  },
  {
    title: "Word Break",
    entries: [
      {
        class: "break-normal",
        css: "overflow-wrap: normal; word-break: normal",
      },
      { class: "break-words", css: "overflow-wrap: break-word" },
      { class: "break-all", css: "word-break: break-all" },
      { class: "break-keep", css: "word-break: keep-all" },
    ],
  },
  {
    title: "Hyphens",
    entries: [
      { class: "hyphens-none", css: "hyphens: none" },
      { class: "hyphens-manual", css: "hyphens: manual" },
      { class: "hyphens-auto", css: "hyphens: auto" },
    ],
  },
  {
    title: "List Style",
    entries: [
      { class: "list-none", css: "list-style-type: none" },
      { class: "list-disc", css: "list-style-type: disc" },
      { class: "list-decimal", css: "list-style-type: decimal" },
      { class: "list-inside", css: "list-style-position: inside" },
      { class: "list-outside", css: "list-style-position: outside" },
    ],
  },
  {
    title: "Content",
    entries: [{ class: "content-none", css: "content: none" }],
  },
  // ─── BACKGROUNDS ──────────────────────────────────────────────────────────
  {
    title: "Background Attachment",
    entries: [
      { class: "bg-fixed", css: "background-attachment: fixed" },
      { class: "bg-local", css: "background-attachment: local" },
      { class: "bg-scroll", css: "background-attachment: scroll" },
    ],
  },
  {
    title: "Background Clip",
    entries: [
      { class: "bg-clip-border", css: "background-clip: border-box" },
      { class: "bg-clip-padding", css: "background-clip: padding-box" },
      { class: "bg-clip-content", css: "background-clip: content-box" },
      { class: "bg-clip-text", css: "background-clip: text" },
    ],
  },
  {
    title: "Background Origin",
    entries: [
      { class: "bg-origin-border", css: "background-origin: border-box" },
      { class: "bg-origin-padding", css: "background-origin: padding-box" },
      { class: "bg-origin-content", css: "background-origin: content-box" },
    ],
  },
  {
    title: "Background Position",
    entries: [
      { class: "bg-bottom", css: "background-position: bottom" },
      { class: "bg-center", css: "background-position: center" },
      { class: "bg-left", css: "background-position: left" },
      { class: "bg-left-bottom", css: "background-position: left bottom" },
      { class: "bg-left-top", css: "background-position: left top" },
      { class: "bg-right", css: "background-position: right" },
      { class: "bg-right-bottom", css: "background-position: right bottom" },
      { class: "bg-right-top", css: "background-position: right top" },
      { class: "bg-top", css: "background-position: top" },
    ],
  },
  {
    title: "Background Repeat",
    entries: [
      { class: "bg-repeat", css: "background-repeat: repeat" },
      { class: "bg-no-repeat", css: "background-repeat: no-repeat" },
      { class: "bg-repeat-x", css: "background-repeat: repeat-x" },
      { class: "bg-repeat-y", css: "background-repeat: repeat-y" },
      { class: "bg-repeat-space", css: "background-repeat: space" },
      { class: "bg-repeat-round", css: "background-repeat: round" },
    ],
  },
  {
    title: "Background Size",
    entries: [
      { class: "bg-auto", css: "background-size: auto" },
      { class: "bg-cover", css: "background-size: cover" },
      { class: "bg-contain", css: "background-size: contain" },
    ],
  },
  {
    title: "Background Image",
    entries: [
      { class: "bg-none", css: "background-image: none" },
      {
        class: "bg-gradient-to-t",
        css: "background-image: linear-gradient(to top, ...)",
      },
      {
        class: "bg-gradient-to-tr",
        css: "background-image: linear-gradient(to top right, ...)",
      },
      {
        class: "bg-gradient-to-r",
        css: "background-image: linear-gradient(to right, ...)",
      },
      {
        class: "bg-gradient-to-br",
        css: "background-image: linear-gradient(to bottom right, ...)",
      },
      {
        class: "bg-gradient-to-b",
        css: "background-image: linear-gradient(to bottom, ...)",
      },
      {
        class: "bg-gradient-to-bl",
        css: "background-image: linear-gradient(to bottom left, ...)",
      },
      {
        class: "bg-gradient-to-l",
        css: "background-image: linear-gradient(to left, ...)",
      },
      {
        class: "bg-gradient-to-tl",
        css: "background-image: linear-gradient(to top left, ...)",
      },
      { class: "from-{color}", css: "--tw-gradient-from: {color}" },
      { class: "via-{color}", css: "--tw-gradient-via: {color}" },
      { class: "to-{color}", css: "--tw-gradient-to: {color}" },
      { class: "from-0%", css: "--tw-gradient-from-position: 0%" },
      { class: "via-50%", css: "--tw-gradient-via-position: 50%" },
      { class: "to-100%", css: "--tw-gradient-to-position: 100%" },
    ],
  },
  // ─── BORDERS ──────────────────────────────────────────────────────────────
  {
    title: "Border Radius",
    entries: [
      { class: "rounded-none", css: "border-radius: 0px" },
      { class: "rounded-sm", css: "border-radius: 0.125rem" },
      { class: "rounded", css: "border-radius: 0.25rem" },
      { class: "rounded-md", css: "border-radius: 0.375rem" },
      { class: "rounded-lg", css: "border-radius: 0.5rem" },
      { class: "rounded-xl", css: "border-radius: 0.75rem" },
      { class: "rounded-2xl", css: "border-radius: 1rem" },
      { class: "rounded-3xl", css: "border-radius: 1.5rem" },
      { class: "rounded-full", css: "border-radius: 9999px" },
      {
        class: "rounded-t-lg",
        css: "border-top-left-radius: 0.5rem; border-top-right-radius: 0.5rem",
      },
      {
        class: "rounded-b-lg",
        css: "border-bottom-left-radius: 0.5rem; border-bottom-right-radius: 0.5rem",
      },
      {
        class: "rounded-l-lg",
        css: "border-top-left-radius: 0.5rem; border-bottom-left-radius: 0.5rem",
      },
      {
        class: "rounded-r-lg",
        css: "border-top-right-radius: 0.5rem; border-bottom-right-radius: 0.5rem",
      },
      { class: "rounded-tl-lg", css: "border-top-left-radius: 0.5rem" },
      { class: "rounded-tr-lg", css: "border-top-right-radius: 0.5rem" },
      { class: "rounded-bl-lg", css: "border-bottom-left-radius: 0.5rem" },
      { class: "rounded-br-lg", css: "border-bottom-right-radius: 0.5rem" },
    ],
  },
  {
    title: "Border Width",
    entries: [
      { class: "border-0", css: "border-width: 0px" },
      { class: "border", css: "border-width: 1px" },
      { class: "border-2", css: "border-width: 2px" },
      { class: "border-4", css: "border-width: 4px" },
      { class: "border-8", css: "border-width: 8px" },
      { class: "border-t", css: "border-top-width: 1px" },
      { class: "border-r", css: "border-right-width: 1px" },
      { class: "border-b", css: "border-bottom-width: 1px" },
      { class: "border-l", css: "border-left-width: 1px" },
      { class: "border-t-2", css: "border-top-width: 2px" },
      { class: "border-b-4", css: "border-bottom-width: 4px" },
      {
        class: "border-x",
        css: "border-left-width: 1px; border-right-width: 1px",
      },
      {
        class: "border-y",
        css: "border-top-width: 1px; border-bottom-width: 1px",
      },
    ],
  },
  {
    title: "Border Style",
    entries: [
      { class: "border-solid", css: "border-style: solid" },
      { class: "border-dashed", css: "border-style: dashed" },
      { class: "border-dotted", css: "border-style: dotted" },
      { class: "border-double", css: "border-style: double" },
      { class: "border-hidden", css: "border-style: hidden" },
      { class: "border-none", css: "border-style: none" },
    ],
  },
  {
    title: "Divide",
    entries: [
      { class: "divide-x", css: "border-left-width: 1px (between children)" },
      { class: "divide-x-2", css: "border-left-width: 2px (between children)" },
      { class: "divide-y", css: "border-top-width: 1px (between children)" },
      { class: "divide-y-2", css: "border-top-width: 2px (between children)" },
      { class: "divide-solid", css: "border-style: solid (between children)" },
      {
        class: "divide-dashed",
        css: "border-style: dashed (between children)",
      },
      {
        class: "divide-dotted",
        css: "border-style: dotted (between children)",
      },
    ],
  },
  {
    title: "Outline",
    entries: [
      {
        class: "outline-none",
        css: "outline: 2px solid transparent; outline-offset: 2px",
      },
      { class: "outline", css: "outline-style: solid" },
      { class: "outline-dashed", css: "outline-style: dashed" },
      { class: "outline-dotted", css: "outline-style: dotted" },
      { class: "outline-double", css: "outline-style: double" },
      { class: "outline-0", css: "outline-width: 0px" },
      { class: "outline-1", css: "outline-width: 1px" },
      { class: "outline-2", css: "outline-width: 2px" },
      { class: "outline-4", css: "outline-width: 4px" },
      { class: "outline-offset-0", css: "outline-offset: 0px" },
      { class: "outline-offset-2", css: "outline-offset: 2px" },
      { class: "outline-offset-4", css: "outline-offset: 4px" },
    ],
  },
  {
    title: "Ring",
    entries: [
      {
        class: "ring-0",
        css: "box-shadow: var(--tw-ring-inset) 0 0 0 0px ...",
      },
      {
        class: "ring-1",
        css: "box-shadow: var(--tw-ring-inset) 0 0 0 1px ...",
      },
      {
        class: "ring-2",
        css: "box-shadow: var(--tw-ring-inset) 0 0 0 2px ...",
      },
      { class: "ring", css: "box-shadow: var(--tw-ring-inset) 0 0 0 3px ..." },
      {
        class: "ring-4",
        css: "box-shadow: var(--tw-ring-inset) 0 0 0 4px ...",
      },
      {
        class: "ring-8",
        css: "box-shadow: var(--tw-ring-inset) 0 0 0 8px ...",
      },
      { class: "ring-inset", css: "--tw-ring-inset: inset" },
      { class: "ring-offset-0", css: "--tw-ring-offset-width: 0px" },
      { class: "ring-offset-2", css: "--tw-ring-offset-width: 2px" },
      { class: "ring-offset-4", css: "--tw-ring-offset-width: 4px" },
    ],
  },
  // ─── EFFECTS ──────────────────────────────────────────────────────────────
  {
    title: "Box Shadow",
    entries: [
      { class: "shadow-none", css: "box-shadow: none" },
      { class: "shadow-sm", css: "box-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05)" },
      {
        class: "shadow",
        css: "box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      },
      {
        class: "shadow-md",
        css: "box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      },
      {
        class: "shadow-lg",
        css: "box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      },
      {
        class: "shadow-xl",
        css: "box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
      },
      {
        class: "shadow-2xl",
        css: "box-shadow: 0 25px 50px -12px rgb(0 0 0 / 0.25)",
      },
      {
        class: "shadow-inner",
        css: "box-shadow: inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
      },
    ],
  },
  {
    title: "Opacity",
    entries: [
      { class: "opacity-0", css: "opacity: 0" },
      { class: "opacity-5", css: "opacity: 0.05" },
      { class: "opacity-10", css: "opacity: 0.1" },
      { class: "opacity-20", css: "opacity: 0.2" },
      { class: "opacity-25", css: "opacity: 0.25" },
      { class: "opacity-30", css: "opacity: 0.3" },
      { class: "opacity-40", css: "opacity: 0.4" },
      { class: "opacity-50", css: "opacity: 0.5" },
      { class: "opacity-60", css: "opacity: 0.6" },
      { class: "opacity-70", css: "opacity: 0.7" },
      { class: "opacity-75", css: "opacity: 0.75" },
      { class: "opacity-80", css: "opacity: 0.8" },
      { class: "opacity-90", css: "opacity: 0.9" },
      { class: "opacity-95", css: "opacity: 0.95" },
      { class: "opacity-100", css: "opacity: 1" },
    ],
  },
  {
    title: "Mix Blend Mode",
    entries: [
      { class: "mix-blend-normal", css: "mix-blend-mode: normal" },
      { class: "mix-blend-multiply", css: "mix-blend-mode: multiply" },
      { class: "mix-blend-screen", css: "mix-blend-mode: screen" },
      { class: "mix-blend-overlay", css: "mix-blend-mode: overlay" },
      { class: "mix-blend-darken", css: "mix-blend-mode: darken" },
      { class: "mix-blend-lighten", css: "mix-blend-mode: lighten" },
      { class: "mix-blend-color-dodge", css: "mix-blend-mode: color-dodge" },
      { class: "mix-blend-color-burn", css: "mix-blend-mode: color-burn" },
      { class: "mix-blend-hard-light", css: "mix-blend-mode: hard-light" },
      { class: "mix-blend-soft-light", css: "mix-blend-mode: soft-light" },
      { class: "mix-blend-difference", css: "mix-blend-mode: difference" },
      { class: "mix-blend-exclusion", css: "mix-blend-mode: exclusion" },
      { class: "mix-blend-hue", css: "mix-blend-mode: hue" },
      { class: "mix-blend-saturation", css: "mix-blend-mode: saturation" },
      { class: "mix-blend-color", css: "mix-blend-mode: color" },
      { class: "mix-blend-luminosity", css: "mix-blend-mode: luminosity" },
      { class: "mix-blend-plus-darker", css: "mix-blend-mode: plus-darker" },
      { class: "mix-blend-plus-lighter", css: "mix-blend-mode: plus-lighter" },
    ],
  },
  {
    title: "Background Blend Mode",
    entries: [
      { class: "bg-blend-normal", css: "background-blend-mode: normal" },
      { class: "bg-blend-multiply", css: "background-blend-mode: multiply" },
      { class: "bg-blend-screen", css: "background-blend-mode: screen" },
      { class: "bg-blend-overlay", css: "background-blend-mode: overlay" },
      { class: "bg-blend-darken", css: "background-blend-mode: darken" },
      { class: "bg-blend-lighten", css: "background-blend-mode: lighten" },
      {
        class: "bg-blend-color-dodge",
        css: "background-blend-mode: color-dodge",
      },
      {
        class: "bg-blend-color-burn",
        css: "background-blend-mode: color-burn",
      },
      {
        class: "bg-blend-hard-light",
        css: "background-blend-mode: hard-light",
      },
      {
        class: "bg-blend-difference",
        css: "background-blend-mode: difference",
      },
      { class: "bg-blend-hue", css: "background-blend-mode: hue" },
      {
        class: "bg-blend-luminosity",
        css: "background-blend-mode: luminosity",
      },
    ],
  },
  // ─── FILTERS ──────────────────────────────────────────────────────────────
  {
    title: "Filter",
    entries: [
      {
        class: "filter",
        css: "filter: var(--tw-blur) var(--tw-brightness) ...",
      },
      { class: "filter-none", css: "filter: none" },
      { class: "blur-none", css: "filter: blur(0)" },
      { class: "blur-sm", css: "filter: blur(4px)" },
      { class: "blur", css: "filter: blur(8px)" },
      { class: "blur-md", css: "filter: blur(12px)" },
      { class: "blur-lg", css: "filter: blur(16px)" },
      { class: "blur-xl", css: "filter: blur(24px)" },
      { class: "blur-2xl", css: "filter: blur(40px)" },
      { class: "blur-3xl", css: "filter: blur(64px)" },
      { class: "brightness-0", css: "filter: brightness(0)" },
      { class: "brightness-50", css: "filter: brightness(.5)" },
      { class: "brightness-75", css: "filter: brightness(.75)" },
      { class: "brightness-90", css: "filter: brightness(.9)" },
      { class: "brightness-95", css: "filter: brightness(.95)" },
      { class: "brightness-100", css: "filter: brightness(1)" },
      { class: "brightness-105", css: "filter: brightness(1.05)" },
      { class: "brightness-110", css: "filter: brightness(1.1)" },
      { class: "brightness-125", css: "filter: brightness(1.25)" },
      { class: "brightness-150", css: "filter: brightness(1.5)" },
      { class: "brightness-200", css: "filter: brightness(2)" },
      { class: "contrast-0", css: "filter: contrast(0)" },
      { class: "contrast-50", css: "filter: contrast(.5)" },
      { class: "contrast-100", css: "filter: contrast(1)" },
      { class: "contrast-125", css: "filter: contrast(1.25)" },
      { class: "contrast-150", css: "filter: contrast(1.5)" },
      { class: "contrast-200", css: "filter: contrast(2)" },
      { class: "drop-shadow-none", css: "filter: drop-shadow(0 0 #0000)" },
      {
        class: "drop-shadow-sm",
        css: "filter: drop-shadow(0 1px 1px rgb(0 0 0/0.05))",
      },
      {
        class: "drop-shadow",
        css: "filter: drop-shadow(0 1px 2px rgb(0 0 0/0.1)) drop-shadow(0 1px 1px rgb(0 0 0/0.06))",
      },
      {
        class: "drop-shadow-md",
        css: "filter: drop-shadow(0 4px 3px rgb(0 0 0/0.07)) ...",
      },
      {
        class: "drop-shadow-lg",
        css: "filter: drop-shadow(0 10px 8px rgb(0 0 0/0.04)) ...",
      },
      {
        class: "drop-shadow-xl",
        css: "filter: drop-shadow(0 20px 13px rgb(0 0 0/0.03)) ...",
      },
      {
        class: "drop-shadow-2xl",
        css: "filter: drop-shadow(0 25px 25px rgb(0 0 0/0.15))",
      },
      { class: "grayscale-0", css: "filter: grayscale(0)" },
      { class: "grayscale", css: "filter: grayscale(100%)" },
      { class: "hue-rotate-0", css: "filter: hue-rotate(0deg)" },
      { class: "hue-rotate-15", css: "filter: hue-rotate(15deg)" },
      { class: "hue-rotate-30", css: "filter: hue-rotate(30deg)" },
      { class: "hue-rotate-60", css: "filter: hue-rotate(60deg)" },
      { class: "hue-rotate-90", css: "filter: hue-rotate(90deg)" },
      { class: "hue-rotate-180", css: "filter: hue-rotate(180deg)" },
      { class: "invert-0", css: "filter: invert(0)" },
      { class: "invert", css: "filter: invert(100%)" },
      { class: "saturate-0", css: "filter: saturate(0)" },
      { class: "saturate-50", css: "filter: saturate(.5)" },
      { class: "saturate-100", css: "filter: saturate(1)" },
      { class: "saturate-150", css: "filter: saturate(1.5)" },
      { class: "saturate-200", css: "filter: saturate(2)" },
      { class: "sepia-0", css: "filter: sepia(0)" },
      { class: "sepia", css: "filter: sepia(100%)" },
    ],
  },
  {
    title: "Backdrop Filter",
    entries: [
      { class: "backdrop-blur-none", css: "backdrop-filter: blur(0)" },
      { class: "backdrop-blur-sm", css: "backdrop-filter: blur(4px)" },
      { class: "backdrop-blur", css: "backdrop-filter: blur(8px)" },
      { class: "backdrop-blur-md", css: "backdrop-filter: blur(12px)" },
      { class: "backdrop-blur-lg", css: "backdrop-filter: blur(16px)" },
      { class: "backdrop-blur-xl", css: "backdrop-filter: blur(24px)" },
      { class: "backdrop-blur-2xl", css: "backdrop-filter: blur(40px)" },
      { class: "backdrop-blur-3xl", css: "backdrop-filter: blur(64px)" },
      {
        class: "backdrop-brightness-100",
        css: "backdrop-filter: brightness(1)",
      },
      { class: "backdrop-contrast-100", css: "backdrop-filter: contrast(1)" },
      { class: "backdrop-grayscale", css: "backdrop-filter: grayscale(100%)" },
      {
        class: "backdrop-hue-rotate-30",
        css: "backdrop-filter: hue-rotate(30deg)",
      },
      { class: "backdrop-invert", css: "backdrop-filter: invert(100%)" },
      { class: "backdrop-opacity-50", css: "backdrop-filter: opacity(.5)" },
      { class: "backdrop-saturate-150", css: "backdrop-filter: saturate(1.5)" },
      { class: "backdrop-sepia", css: "backdrop-filter: sepia(100%)" },
    ],
  },
  // ─── TABLES ───────────────────────────────────────────────────────────────
  {
    title: "Tables",
    entries: [
      { class: "border-collapse", css: "border-collapse: collapse" },
      { class: "border-separate", css: "border-collapse: separate" },
      { class: "border-spacing-0", css: "border-spacing: 0px 0px" },
      { class: "border-spacing-2", css: "border-spacing: 0.5rem 0.5rem" },
      { class: "table-auto", css: "table-layout: auto" },
      { class: "table-fixed", css: "table-layout: fixed" },
      { class: "caption-top", css: "caption-side: top" },
      { class: "caption-bottom", css: "caption-side: bottom" },
    ],
  },
  // ─── TRANSITIONS & ANIMATIONS ─────────────────────────────────────────────
  {
    title: "Transition",
    entries: [
      { class: "transition-none", css: "transition-property: none" },
      {
        class: "transition-all",
        css: "transition-property: all; duration: 150ms; timing: cubic-bezier(0.4, 0, 0.2, 1)",
      },
      {
        class: "transition",
        css: "transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter; duration: 150ms",
      },
      {
        class: "transition-colors",
        css: "transition-property: color, background-color, border-color, text-decoration-color, fill, stroke; duration: 150ms",
      },
      {
        class: "transition-opacity",
        css: "transition-property: opacity; duration: 150ms",
      },
      {
        class: "transition-shadow",
        css: "transition-property: box-shadow; duration: 150ms",
      },
      {
        class: "transition-transform",
        css: "transition-property: transform; duration: 150ms",
      },
    ],
  },
  {
    title: "Duration & Easing",
    entries: [
      { class: "duration-0", css: "transition-duration: 0s" },
      { class: "duration-75", css: "transition-duration: 75ms" },
      { class: "duration-100", css: "transition-duration: 100ms" },
      { class: "duration-150", css: "transition-duration: 150ms" },
      { class: "duration-200", css: "transition-duration: 200ms" },
      { class: "duration-300", css: "transition-duration: 300ms" },
      { class: "duration-500", css: "transition-duration: 500ms" },
      { class: "duration-700", css: "transition-duration: 700ms" },
      { class: "duration-1000", css: "transition-duration: 1000ms" },
      { class: "ease-linear", css: "transition-timing-function: linear" },
      {
        class: "ease-in",
        css: "transition-timing-function: cubic-bezier(0.4, 0, 1, 1)",
      },
      {
        class: "ease-out",
        css: "transition-timing-function: cubic-bezier(0, 0, 0.2, 1)",
      },
      {
        class: "ease-in-out",
        css: "transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1)",
      },
      { class: "delay-0", css: "transition-delay: 0s" },
      { class: "delay-75", css: "transition-delay: 75ms" },
      { class: "delay-100", css: "transition-delay: 100ms" },
      { class: "delay-150", css: "transition-delay: 150ms" },
      { class: "delay-200", css: "transition-delay: 200ms" },
      { class: "delay-300", css: "transition-delay: 300ms" },
      { class: "delay-500", css: "transition-delay: 500ms" },
      { class: "delay-700", css: "transition-delay: 700ms" },
      { class: "delay-1000", css: "transition-delay: 1000ms" },
    ],
  },
  {
    title: "Animation",
    entries: [
      { class: "animate-none", css: "animation: none" },
      { class: "animate-spin", css: "animation: spin 1s linear infinite" },
      {
        class: "animate-ping",
        css: "animation: ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      },
      {
        class: "animate-pulse",
        css: "animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      { class: "animate-bounce", css: "animation: bounce 1s infinite" },
    ],
  },
  // ─── TRANSFORMS ───────────────────────────────────────────────────────────
  {
    title: "Scale",
    entries: [
      { class: "scale-0", css: "transform: scale(0)" },
      { class: "scale-50", css: "transform: scale(.5)" },
      { class: "scale-75", css: "transform: scale(.75)" },
      { class: "scale-90", css: "transform: scale(.9)" },
      { class: "scale-95", css: "transform: scale(.95)" },
      { class: "scale-100", css: "transform: scale(1)" },
      { class: "scale-105", css: "transform: scale(1.05)" },
      { class: "scale-110", css: "transform: scale(1.1)" },
      { class: "scale-125", css: "transform: scale(1.25)" },
      { class: "scale-150", css: "transform: scale(1.5)" },
      { class: "scale-x-75", css: "transform: scaleX(.75)" },
      { class: "scale-y-75", css: "transform: scaleY(.75)" },
    ],
  },
  {
    title: "Rotate",
    entries: [
      { class: "rotate-0", css: "transform: rotate(0deg)" },
      { class: "rotate-1", css: "transform: rotate(1deg)" },
      { class: "rotate-2", css: "transform: rotate(2deg)" },
      { class: "rotate-3", css: "transform: rotate(3deg)" },
      { class: "rotate-6", css: "transform: rotate(6deg)" },
      { class: "rotate-12", css: "transform: rotate(12deg)" },
      { class: "rotate-45", css: "transform: rotate(45deg)" },
      { class: "rotate-90", css: "transform: rotate(90deg)" },
      { class: "rotate-180", css: "transform: rotate(180deg)" },
      { class: "-rotate-45", css: "transform: rotate(-45deg)" },
      { class: "-rotate-90", css: "transform: rotate(-90deg)" },
    ],
  },
  {
    title: "Translate",
    entries: [
      { class: "translate-x-0", css: "transform: translateX(0px)" },
      { class: "translate-x-px", css: "transform: translateX(1px)" },
      { class: "translate-x-1", css: "transform: translateX(0.25rem)" },
      { class: "translate-x-4", css: "transform: translateX(1rem)" },
      { class: "translate-x-8", css: "transform: translateX(2rem)" },
      { class: "translate-x-1/2", css: "transform: translateX(50%)" },
      { class: "translate-x-full", css: "transform: translateX(100%)" },
      { class: "-translate-x-full", css: "transform: translateX(-100%)" },
      { class: "translate-y-0", css: "transform: translateY(0px)" },
      { class: "translate-y-4", css: "transform: translateY(1rem)" },
      { class: "translate-y-1/2", css: "transform: translateY(50%)" },
      { class: "translate-y-full", css: "transform: translateY(100%)" },
      { class: "-translate-y-full", css: "transform: translateY(-100%)" },
    ],
  },
  {
    title: "Skew",
    entries: [
      { class: "skew-x-0", css: "transform: skewX(0deg)" },
      { class: "skew-x-1", css: "transform: skewX(1deg)" },
      { class: "skew-x-2", css: "transform: skewX(2deg)" },
      { class: "skew-x-3", css: "transform: skewX(3deg)" },
      { class: "skew-x-6", css: "transform: skewX(6deg)" },
      { class: "skew-x-12", css: "transform: skewX(12deg)" },
      { class: "skew-y-0", css: "transform: skewY(0deg)" },
      { class: "skew-y-3", css: "transform: skewY(3deg)" },
      { class: "skew-y-6", css: "transform: skewY(6deg)" },
      { class: "skew-y-12", css: "transform: skewY(12deg)" },
    ],
  },
  {
    title: "Transform Origin",
    entries: [
      { class: "origin-center", css: "transform-origin: center" },
      { class: "origin-top", css: "transform-origin: top" },
      { class: "origin-top-right", css: "transform-origin: top right" },
      { class: "origin-right", css: "transform-origin: right" },
      { class: "origin-bottom-right", css: "transform-origin: bottom right" },
      { class: "origin-bottom", css: "transform-origin: bottom" },
      { class: "origin-bottom-left", css: "transform-origin: bottom left" },
      { class: "origin-left", css: "transform-origin: left" },
      { class: "origin-top-left", css: "transform-origin: top left" },
    ],
  },
  // ─── INTERACTIVITY ────────────────────────────────────────────────────────
  {
    title: "Cursor",
    entries: [
      { class: "cursor-auto", css: "cursor: auto" },
      { class: "cursor-default", css: "cursor: default" },
      { class: "cursor-pointer", css: "cursor: pointer" },
      { class: "cursor-wait", css: "cursor: wait" },
      { class: "cursor-text", css: "cursor: text" },
      { class: "cursor-move", css: "cursor: move" },
      { class: "cursor-help", css: "cursor: help" },
      { class: "cursor-not-allowed", css: "cursor: not-allowed" },
      { class: "cursor-none", css: "cursor: none" },
      { class: "cursor-context-menu", css: "cursor: context-menu" },
      { class: "cursor-progress", css: "cursor: progress" },
      { class: "cursor-cell", css: "cursor: cell" },
      { class: "cursor-crosshair", css: "cursor: crosshair" },
      { class: "cursor-vertical-text", css: "cursor: vertical-text" },
      { class: "cursor-alias", css: "cursor: alias" },
      { class: "cursor-copy", css: "cursor: copy" },
      { class: "cursor-no-drop", css: "cursor: no-drop" },
      { class: "cursor-grab", css: "cursor: grab" },
      { class: "cursor-grabbing", css: "cursor: grabbing" },
      { class: "cursor-zoom-in", css: "cursor: zoom-in" },
      { class: "cursor-zoom-out", css: "cursor: zoom-out" },
    ],
  },
  {
    title: "Pointer Events",
    entries: [
      { class: "pointer-events-none", css: "pointer-events: none" },
      { class: "pointer-events-auto", css: "pointer-events: auto" },
    ],
  },
  {
    title: "User Select",
    entries: [
      { class: "select-none", css: "user-select: none" },
      { class: "select-text", css: "user-select: text" },
      { class: "select-all", css: "user-select: all" },
      { class: "select-auto", css: "user-select: auto" },
    ],
  },
  {
    title: "Resize",
    entries: [
      { class: "resize-none", css: "resize: none" },
      { class: "resize", css: "resize: both" },
      { class: "resize-y", css: "resize: vertical" },
      { class: "resize-x", css: "resize: horizontal" },
    ],
  },
  {
    title: "Scroll Behavior",
    entries: [
      { class: "scroll-auto", css: "scroll-behavior: auto" },
      { class: "scroll-smooth", css: "scroll-behavior: smooth" },
    ],
  },
  {
    title: "Scroll Snap",
    entries: [
      { class: "snap-none", css: "scroll-snap-type: none" },
      {
        class: "snap-x",
        css: "scroll-snap-type: x var(--tw-scroll-snap-strictness)",
      },
      {
        class: "snap-y",
        css: "scroll-snap-type: y var(--tw-scroll-snap-strictness)",
      },
      {
        class: "snap-both",
        css: "scroll-snap-type: both var(--tw-scroll-snap-strictness)",
      },
      {
        class: "snap-mandatory",
        css: "--tw-scroll-snap-strictness: mandatory",
      },
      {
        class: "snap-proximity",
        css: "--tw-scroll-snap-strictness: proximity",
      },
      { class: "snap-start", css: "scroll-snap-align: start" },
      { class: "snap-end", css: "scroll-snap-align: end" },
      { class: "snap-center", css: "scroll-snap-align: center" },
      { class: "snap-align-none", css: "scroll-snap-align: none" },
      { class: "snap-normal", css: "scroll-snap-stop: normal" },
      { class: "snap-always", css: "scroll-snap-stop: always" },
    ],
  },
  {
    title: "Scroll Margin & Padding",
    entries: [
      { class: "scroll-m-4", css: "scroll-margin: 1rem" },
      { class: "scroll-mt-4", css: "scroll-margin-top: 1rem" },
      { class: "scroll-mr-4", css: "scroll-margin-right: 1rem" },
      { class: "scroll-mb-4", css: "scroll-margin-bottom: 1rem" },
      { class: "scroll-ml-4", css: "scroll-margin-left: 1rem" },
      { class: "scroll-p-4", css: "scroll-padding: 1rem" },
      { class: "scroll-pt-4", css: "scroll-padding-top: 1rem" },
      { class: "scroll-pr-4", css: "scroll-padding-right: 1rem" },
      { class: "scroll-pb-4", css: "scroll-padding-bottom: 1rem" },
      { class: "scroll-pl-4", css: "scroll-padding-left: 1rem" },
    ],
  },
  {
    title: "Touch Action",
    entries: [
      { class: "touch-auto", css: "touch-action: auto" },
      { class: "touch-none", css: "touch-action: none" },
      { class: "touch-pan-x", css: "touch-action: pan-x" },
      { class: "touch-pan-y", css: "touch-action: pan-y" },
      { class: "touch-pan-left", css: "touch-action: pan-left" },
      { class: "touch-pan-right", css: "touch-action: pan-right" },
      { class: "touch-pan-up", css: "touch-action: pan-up" },
      { class: "touch-pan-down", css: "touch-action: pan-down" },
      { class: "touch-pinch-zoom", css: "touch-action: pinch-zoom" },
      { class: "touch-manipulation", css: "touch-action: manipulation" },
    ],
  },
  {
    title: "Will Change",
    entries: [
      { class: "will-change-auto", css: "will-change: auto" },
      { class: "will-change-scroll", css: "will-change: scroll-position" },
      { class: "will-change-contents", css: "will-change: contents" },
      { class: "will-change-transform", css: "will-change: transform" },
    ],
  },
  {
    title: "Appearance",
    entries: [
      { class: "appearance-none", css: "appearance: none" },
      { class: "appearance-auto", css: "appearance: auto" },
    ],
  },
  {
    title: "Accent & Caret Color",
    entries: [
      { class: "accent-auto", css: "accent-color: auto" },
      { class: "accent-inherit", css: "accent-color: inherit" },
      { class: "accent-current", css: "accent-color: currentColor" },
      { class: "accent-{color}", css: "accent-color: {color}" },
      { class: "caret-auto", css: "caret-color: auto" },
      { class: "caret-inherit", css: "caret-color: inherit" },
      { class: "caret-current", css: "caret-color: currentColor" },
      { class: "caret-{color}", css: "caret-color: {color}" },
    ],
  },
  // ─── SVG ──────────────────────────────────────────────────────────────────
  {
    title: "SVG",
    entries: [
      { class: "fill-none", css: "fill: none" },
      { class: "fill-inherit", css: "fill: inherit" },
      { class: "fill-current", css: "fill: currentColor" },
      { class: "fill-{color}", css: "fill: {color}" },
      { class: "stroke-none", css: "stroke: none" },
      { class: "stroke-inherit", css: "stroke: inherit" },
      { class: "stroke-current", css: "stroke: currentColor" },
      { class: "stroke-{color}", css: "stroke: {color}" },
      { class: "stroke-0", css: "stroke-width: 0" },
      { class: "stroke-1", css: "stroke-width: 1" },
      { class: "stroke-2", css: "stroke-width: 2" },
    ],
  },
  // ─── ACCESSIBILITY ────────────────────────────────────────────────────────
  {
    title: "Accessibility",
    entries: [
      {
        class: "sr-only",
        css: "position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border-width: 0",
      },
      {
        class: "not-sr-only",
        css: "position: static; width: auto; height: auto; padding: 0; margin: 0; overflow: visible; clip: auto; white-space: normal",
      },
      { class: "forced-color-adjust-auto", css: "forced-color-adjust: auto" },
      { class: "forced-color-adjust-none", css: "forced-color-adjust: none" },
    ],
  },
  // ─── MODIFIERS ────────────────────────────────────────────────────────────
  {
    title: "Responsive Breakpoints",
    entries: [
      { class: "sm:{utility}", css: "@media (min-width: 640px)" },
      { class: "md:{utility}", css: "@media (min-width: 768px)" },
      { class: "lg:{utility}", css: "@media (min-width: 1024px)" },
      { class: "xl:{utility}", css: "@media (min-width: 1280px)" },
      { class: "2xl:{utility}", css: "@media (min-width: 1536px)" },
      { class: "max-sm:{utility}", css: "@media (max-width: 639px)" },
      { class: "max-md:{utility}", css: "@media (max-width: 767px)" },
      { class: "max-lg:{utility}", css: "@media (max-width: 1023px)" },
    ],
  },
  {
    title: "State Modifiers",
    entries: [
      { class: "hover:{utility}", css: ":hover" },
      { class: "focus:{utility}", css: ":focus" },
      { class: "focus-within:{utility}", css: ":focus-within" },
      { class: "focus-visible:{utility}", css: ":focus-visible" },
      { class: "active:{utility}", css: ":active" },
      { class: "visited:{utility}", css: ":visited" },
      { class: "disabled:{utility}", css: ":disabled" },
      { class: "checked:{utility}", css: ":checked" },
      { class: "indeterminate:{utility}", css: ":indeterminate" },
      { class: "required:{utility}", css: ":required" },
      { class: "valid:{utility}", css: ":valid" },
      { class: "invalid:{utility}", css: ":invalid" },
      { class: "placeholder-shown:{utility}", css: ":placeholder-shown" },
      { class: "autofill:{utility}", css: ":autofill" },
      { class: "read-only:{utility}", css: ":read-only" },
      { class: "empty:{utility}", css: ":empty" },
      { class: "first:{utility}", css: ":first-child" },
      { class: "last:{utility}", css: ":last-child" },
      { class: "only:{utility}", css: ":only-child" },
      { class: "odd:{utility}", css: ":nth-child(odd)" },
      { class: "even:{utility}", css: ":nth-child(even)" },
    ],
  },
  {
    title: "Group & Peer Modifiers",
    entries: [
      { class: "group", css: "(marker on parent element)" },
      { class: "group-hover:{utility}", css: ".group:hover .{utility}" },
      { class: "group-focus:{utility}", css: ".group:focus .{utility}" },
      { class: "group-active:{utility}", css: ".group:active .{utility}" },
      { class: "group-disabled:{utility}", css: ".group:disabled .{utility}" },
      { class: "peer", css: "(marker on sibling element)" },
      { class: "peer-checked:{utility}", css: ".peer:checked ~ .{utility}" },
      { class: "peer-focus:{utility}", css: ".peer:focus ~ .{utility}" },
      { class: "peer-invalid:{utility}", css: ".peer:invalid ~ .{utility}" },
      { class: "peer-disabled:{utility}", css: ".peer:disabled ~ .{utility}" },
    ],
  },
  {
    title: "Dark Mode & Other Modifiers",
    entries: [
      {
        class: "dark:{utility}",
        css: "@media (prefers-color-scheme: dark) / .dark .{utility}",
      },
      {
        class: "motion-safe:{utility}",
        css: "@media (prefers-reduced-motion: no-preference)",
      },
      {
        class: "motion-reduce:{utility}",
        css: "@media (prefers-reduced-motion: reduce)",
      },
      {
        class: "contrast-more:{utility}",
        css: "@media (prefers-contrast: more)",
      },
      {
        class: "contrast-less:{utility}",
        css: "@media (prefers-contrast: less)",
      },
      { class: "print:{utility}", css: "@media print" },
      { class: "portrait:{utility}", css: "@media (orientation: portrait)" },
      { class: "landscape:{utility}", css: "@media (orientation: landscape)" },
      { class: "rtl:{utility}", css: "[dir='rtl'] .{utility}" },
      { class: "ltr:{utility}", css: "[dir='ltr'] .{utility}" },
      { class: "before:{utility}", css: "::before" },
      { class: "after:{utility}", css: "::after" },
      { class: "placeholder:{utility}", css: "::placeholder" },
      { class: "selection:{utility}", css: "::selection" },
      { class: "first-line:{utility}", css: "::first-line" },
      { class: "first-letter:{utility}", css: "::first-letter" },
      { class: "marker:{utility}", css: "::marker" },
      { class: "backdrop:{utility}", css: "::backdrop" },
    ],
  },
]
